### ISSUE TITLE
cleanning option

### ISSUE THREAD

**Issue by noraj** [Edu4rdSHL/blackarch-devtools#6]
Actually I remove the chroot and setup it back each time I want to try a package to have a clean setup. Do you know if it is possible to add an option for cleaning the chroot?

**Comment by Edu4rdSHL** [comment]
The chroot is synced in every operation with the root chroot install. The only operation that doesn't clean the chroot is the test option because you don't want to reinstall already installed packages when testing. What kind of issue are you having?

See https://github.com/Edu4rdSHL/blackarch-devtools/blob/master/src/functions.rs and note that sync_chroot() function is called in the others functions like build, install, install with missing deps.
